In [1]:
import pandas as pd

In [2]:
df_retail_clients = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/Retail Clients.csv', index_col=False)
df_retail_clients

,Customer ID,Customer Name,Email,Phone,City,State,Country,Age,Gender
0,37249,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,Dortmund,Berlin,Germany,21.0,Male
1,69749,Kelsey Hill,Mark36@gmail.com,6.852900e+09,Nottingham,England,UK,19.0,Female
2,30192,Scott Jensen,Shane85@gmail.com,8.362160e+09,Geelong,New South Wales,Australia,48.0,Male
3,62101,Joseph Miller,Mary34@gmail.com,2.776752e+09,Edmonton,Ontario,Canada,56.0,Male
4,27901,Debra Coleman,Charles30@gmail.com,9.098268e+09,Bristol,England,UK,22.0,Male
...,...,...,...,...,...,...,...,...,...
86157,82768,Patricia Burch,Brian100@gmail.com,8.274071e+09,Denver,Georgia,USA,59.0,Female
86158,14485,Beth Mcknight,James17@gmail.com,1.433775e+09,Glasgow,England,UK,49.0,Female
86159,49840,John Yoder,Anne24@gmail.com,6.134998e+09,Liverpool,England,UK,31.0,Female
86160,58286,Laura Warren,Alison77@gmail.com,1.739610e+09,Sheffield,England,UK,60.0,Female
86161,29845,Austin Hernandez,John40@gmail.com,1.384901e+09,London,Ontario,Canada,51.0,Female

In [3]:
df_retail_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86162 entries, 0 to 86161
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    86162 non-null  int64
 1   Customer Name  86162 non-null  object
 2   Email          86162 non-null  object
 3   Phone          86162 non-null  float64
 4   City           86162 non-null  object
 5   State          86162 non-null  object
 6   Country        86162 non-null  object
 7   Age            86162 non-null  float64
 8   Gender         86162 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB

In [4]:
df_retail_clients = df_retail_clients.dropna()

df_retail_clients['Customer ID'] = df_retail_clients['Customer ID'].astype(int) # Convirtiendo Customer ID en enteros

df_retail_clients.head()

,Customer ID,Customer Name,Email,Phone,City,State,Country,Age,Gender
0,37249,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,Dortmund,Berlin,Germany,21.0,Male
1,69749,Kelsey Hill,Mark36@gmail.com,6.852900e+09,Nottingham,England,UK,19.0,Female
2,30192,Scott Jensen,Shane85@gmail.com,8.362160e+09,Geelong,New South Wales,Australia,48.0,Male
3,62101,Joseph Miller,Mary34@gmail.com,2.776752e+09,Edmonton,Ontario,Canada,56.0,Male
4,27901,Debra Coleman,Charles30@gmail.com,9.098268e+09,Bristol,England,UK,22.0,Male

In [5]:
df_retail_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86162 entries, 0 to 86161
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    86162 non-null  int64
 1   Customer Name  86162 non-null  object
 2   Email          86162 non-null  object
 3   Phone          86162 non-null  float64
 4   City           86162 non-null  object
 5   State          86162 non-null  object
 6   Country        86162 non-null  object
 7   Age            86162 non-null  float64
 8   Gender         86162 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB

In [6]:
df_retail_clients.to_csv('Retail Clients.csv', index=False)

In [7]:
df_retail_sales = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/Retail Sales.csv')
df_retail_sales

,Order ID,Order Date,Customer ID,Product ID,Sales,Quantity,Total_Amount
0,8691788,9/18/2023,37249,1,108.028757,3.0,324.086270
1,2174773,12/31/2023,69749,2,403.353907,2.0,806.707815
2,6679610,4/26/2023,30192,3,354.477600,3.0,1063.432799
3,7232460,5/8/2023,62101,4,352.407717,7.0,2466.854021
4,4983775,1/10/2024,27901,5,124.276524,2.0,248.553049
...,...,...,...,...,...,...,...
297390,4246475,1/20/2024,12104,370,194.792597,5.0,973.962984
297391,1197603,12/28/2023,69772,67,285.137301,1.0,285.137301
297392,7743242,2/27/2024,28449,393,60.701761,3.0,182.105285
297393,9301950,9/3/2023,45477,345,120.834784,1.0,120.834784
297394,2882826,1/8/2024,53626,46,340.319059,7.0,2382.233417

In [8]:
df_retail_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297395 entries, 0 to 297394
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Order ID      297395 non-null  int64
 1   Order Date    297395 non-null  object
 2   Customer ID   297395 non-null  int64
 3   Product ID    297395 non-null  int64
 4   Sales         297395 non-null  float64
 5   Quantity      297395 non-null  float64
 6   Total_Amount  297395 non-null  float64
dtypes: float64(3), int64(3), object(1)
memory usage: 15.9+ MB

In [9]:
df_retail_sales = df_retail_sales.dropna()

df_retail_sales['Order ID'] = df_retail_sales['Order ID'].astype(int)
df_retail_sales['Customer ID'] = df_retail_sales['Customer ID'].astype(int)

In [10]:
df_retail_sales.to_csv('Retail Sales.csv', index=False)

In [11]:
retail_df = pd.read_csv("/content/drive/MyDrive/Asistente IA Data/new_retail_data.csv")
retail_df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,...,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,...,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,...,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,...,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,...,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [12]:
retail_df_products = retail_df[['products','Product_Category','Product_Type','Product_Brand']]
retail_df_products.columns = ['Product Name','Category','Sub-Category','Product_Brand']
retail_df_products_uniques = retail_df_products.drop_duplicates(subset = ['Product Name','Category','Sub-Category','Product_Brand'], keep='first')

In [13]:
# Rellenando los Nan en el DataFrame de products
brand_category_mapping = {
    'Samsung': 'Electronics',
    'Apple': 'Electronics',
    'Sony': 'Electronics',
    'Nestle': 'Grocery',
    'Pepsi': 'Grocery',
    'Coca-Cola': 'Grocery',
    'HarperCollins': 'Books',
    'Random House': 'Books',
    'Penguin Books': 'Books',
    'Adidas': 'Clothing',
    'Zara': 'Clothing',
    'Nike': 'Clothing',
    'Home Depot': 'Home Decor',
    'Bed Bath & Beyond': 'Home Decor',
    'IKEA': 'Home Decor'
}


for brand, category in brand_category_mapping.items():
    retail_df_products_uniques.loc[retail_df_products_uniques['Product_Brand'] == brand, 'Category'] = category

for category in retail_df_products_uniques['Category'].unique():
    retail_df_products_uniques.loc[(retail_df_products_uniques['Category'] == category) & (retail_df_products_uniques['Product_Brand'].isnull()), 'Product_Brand'] = category

<ipython-input-13-b5544e48b357>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_df_products_uniques.loc[retail_df_products_uniques['Product_Brand'] == brand, 'Category'] = category
<ipython-input-13-b5544e48b357>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_df_products_uniques.loc[(retail_df_products_uniques['Category'] == category) & (retail_df_products_uniques['Product_Brand'].isnull()), 'Product_Brand'] = category

In [14]:
retail_df_products_uniques = retail_df_products_uniques.drop_duplicates(subset = ['Product Name','Category','Sub-Category','Product_Brand'], keep='first')
retail_df_products_uniques

             Product Name     Category Sub-Category  Product_Brand
0          Cycling shorts     Clothing       Shorts           Nike
1              Lenovo Tab  Electronics       Tablet        Samsung
2        Sports equipment        Books   Children's  Penguin Books
3           Utility knife   Home Decor        Tools     Home Depot
4       Chocolate cookies      Grocery    Chocolate         Nestle
...                   ...          ...          ...            ...
292844     Legal thriller        Books     Thriller          Books
294125           Affogato      Grocery       Coffee        Grocery
295649            OLED TV  Electronics   Television    Electronics
297410    Building blocks        Books   Children's          Books
297551          Microwave   Home Decor      Kitchen     Home Decor

[656 rows x 4 columns]

In [15]:
num_productos = retail_df_products_uniques.shape[0]
product_ids = range(1, num_productos + 1)
retail_df_products_uniques['Product ID'] = product_ids

In [16]:
# Ordenando el dataframe de products
cols = retail_df_products_uniques.columns.tolist()
cols = cols[-1:] + cols[:-1]
retail_df_products_uniques = retail_df_products_uniques[cols]

In [17]:
retail_df_products_uniques

        Product ID       Product Name     Category Sub-Category  Product_Brand
0                1     Cycling shorts     Clothing       Shorts           Nike
1                2         Lenovo Tab  Electronics       Tablet        Samsung
2                3   Sports equipment        Books   Children's  Penguin Books
3                4      Utility knife   Home Decor        Tools     Home Depot
4                5  Chocolate cookies      Grocery    Chocolate         Nestle
...            ...                ...          ...          ...            ...
292844         652     Legal thriller        Books     Thriller          Books
294125         653           Affogato      Grocery       Coffee        Grocery
295649         654            OLED TV  Electronics   Television    Electronics
297410         655    Building blocks        Books   Children's          Books
297551         656          Microwave   Home Decor      Kitchen     Home Decor

[656 rows x 5 columns]

In [18]:
retail_df_sales = retail_df[['Transaction_ID','Date','Customer_ID','Amount','Total_Purchases','Total_Amount','products','Product_Category','Product_Type','Product_Brand']]
retail_df_sales.columns = ['Order ID','Order Date','Customer ID','Sales','Quantity','Total_Amount','Product Name','Category','Sub-Category','Product_Brand']
retail_df_sales = retail_df_sales.dropna()

retail_df_sales['Order ID'] = retail_df_sales['Order ID'].astype(int)
retail_df_sales['Customer ID'] = retail_df_sales['Customer ID'].astype(int)

<ipython-input-18-a970bff52858>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_df_sales['Order ID'] = retail_df_sales['Order ID'].astype(int)
<ipython-input-18-a970bff52858>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_df_sales['Customer ID'] = retail_df_sales['Customer ID'].astype(int)

In [19]:
retail_df_sales

,Order ID,Order Date,Customer ID,Sales,Quantity,Total_Amount,Product Name,Category,Sub-Category,Product_Brand
0,8691788,9/18/2023,37249,108.028757,3.0,324.086270,Cycling shorts,Clothing,Shorts,Nike
1,2174773,12/31/2023,69749,403.353907,2.0,806.707815,Lenovo Tab,Electronics,Tablet,Samsung
2,6679610,4/26/2023,30192,354.477600,3.0,1063.432799,Sports equipment,Books,Children's,Penguin Books
3,7232460,5/8/2023,62101,352.407717,7.0,2466.854021,Utility knife,Home Decor,Tools,Home Depot
4,4983775,1/10/2024,27901,124.276524,2.0,248.553049,Chocolate cookies,Grocery,Chocolate,Nestle
...,...,...,...,...,...,...,...,...,...,...
302005,4246475,1/20/2024,12104,194.792597,5.0,973.962984,Historical fiction,Books,Fiction,Penguin Books
302006,1197603,12/28/2023,69772,285.137301,1.0,285.137301,LG Gram,Electronics,Laptop,Apple
302007,7743242,2/27/2024,28449,60.701761,3.0,182.105285,Parka,Clothing,Jacket,Adidas
302008,9301950,9/3/2023,45477,120.834784,1.0,120.834784,TV stand,Home Decor,Furniture,IKEA
302009,2882826,1/8/2024,53626,340.319059,7.0,2382.233417,Clocks,Home Decor,Decorations,Home Depot

In [20]:
# Rellenando los Nan en el DataFrame de products
brand_category_mapping = {
    'Samsung': 'Electronics',
    'Apple': 'Electronics',
    'Sony': 'Electronics',
    'Nestle': 'Grocery',
    'Pepsi': 'Grocery',
    'Coca-Cola': 'Grocery',
    'HarperCollins': 'Books',
    'Random House': 'Books',
    'Penguin Books': 'Books',
    'Adidas': 'Clothing',
    'Zara': 'Clothing',
    'Nike': 'Clothing',
    'Home Depot': 'Home Decor',
    'Bed Bath & Beyond': 'Home Decor',
    'IKEA': 'Home Decor'
}


for brand, category in brand_category_mapping.items():
    retail_df_sales.loc[retail_df_sales['Product_Brand'] == brand, 'Category'] = category

for category in retail_df_sales['Category'].unique():
    retail_df_sales.loc[(retail_df_sales['Category'] == category) & (retail_df_sales['Product_Brand'].isnull()), 'Product_Brand'] = category

In [21]:
retail_df_sales = retail_df_sales.merge(retail_df_products_uniques[['Product ID', 'Product Name', 'Category', 'Sub-Category', 'Product_Brand']],
                                               on=['Product Name', 'Category', 'Sub-Category', 'Product_Brand'],
                                               how='left')

In [22]:
retail_df_sales.drop(labels=['Product Name', 'Category', 'Sub-Category', 'Product_Brand'], axis=1,inplace=True)

In [23]:
retail_df_sales=retail_df_sales[['Order ID','Order Date','Customer ID','Product ID','Sales','Quantity','Total_Amount']]

In [24]:
retail_df_sales

,Order ID,Order Date,Customer ID,Product ID,Sales,Quantity,Total_Amount
0,8691788,9/18/2023,37249,1,108.028757,3.0,324.086270
1,2174773,12/31/2023,69749,2,403.353907,2.0,806.707815
2,6679610,4/26/2023,30192,3,354.477600,3.0,1063.432799
3,7232460,5/8/2023,62101,4,352.407717,7.0,2466.854021
4,4983775,1/10/2024,27901,5,124.276524,2.0,248.553049
...,...,...,...,...,...,...,...
299381,4246475,1/20/2024,12104,370,194.792597,5.0,973.962984
299382,1197603,12/28/2023,69772,67,285.137301,1.0,285.137301
299383,7743242,2/27/2024,28449,393,60.701761,3.0,182.105285
299384,9301950,9/3/2023,45477,345,120.834784,1.0,120.834784
299385,2882826,1/8/2024,53626,46,340.319059,7.0,2382.233417

In [25]:
# Filtrando el DF sales para solo incluir los clientes en el DF clients
client_ids_in_df = df_retail_clients['Customer ID'].unique()

retail_df_sales_final = retail_df_sales[retail_df_sales['Customer ID'].isin(client_ids_in_df)]

In [26]:
retail_df_sales_final

,Order ID,Order Date,Customer ID,Product ID,Sales,Quantity,Total_Amount
0,8691788,9/18/2023,37249,1,108.028757,3.0,324.086270
1,2174773,12/31/2023,69749,2,403.353907,2.0,806.707815
2,6679610,4/26/2023,30192,3,354.477600,3.0,1063.432799
3,7232460,5/8/2023,62101,4,352.407717,7.0,2466.854021
4,4983775,1/10/2024,27901,5,124.276524,2.0,248.553049
...,...,...,...,...,...,...,...
299381,4246475,1/20/2024,12104,370,194.792597,5.0,973.962984
299382,1197603,12/28/2023,69772,67,285.137301,1.0,285.137301
299383,7743242,2/27/2024,28449,393,60.701761,3.0,182.105285
299384,9301950,9/3/2023,45477,345,120.834784,1.0,120.834784
299385,2882826,1/8/2024,53626,46,340.319059,7.0,2382.233417

In [27]:
retail_df_sales_final.to_csv('Retail Sales.csv', index=False)

In [28]:
retail_df_products_uniques.drop('Product_Brand', axis=1, inplace=True)

<ipython-input-28-1d3b4775e4ce>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_df_products_uniques.drop('Product_Brand', axis=1, inplace=True)

In [29]:
retail_df_products_uniques.to_csv('Retail Products.csv', index=False)

In [30]:
ecomm_clients = pd.read_csv("/content/drive/MyDrive/Asistente IA Data/ECOMM Clients.csv")
ecomm_clients.head()

  Customer ID     Customer Name           City            State        Country
0    RH-19495       Rick Hansen  New York City         New York  United States
1    JR-16210     Justin Ritter     Wollongong  New South Wales      Australia
2    CR-12730      Craig Reiter       Brisbane       Queensland      Australia
3    KM-16375  Katherine Murray         Berlin           Berlin        Germany
4     RH-9495       Rick Hansen          Dakar            Dakar        Senegal

In [31]:
ecomm_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1590 entries, 0 to 1589
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    1590 non-null   object
 1   Customer Name  1590 non-null   object
 2   City           1590 non-null   object
 3   State          1590 non-null   object
 4   Country        1590 non-null   object
dtypes: object(5)
memory usage: 62.2+ KB

In [32]:
ecomm_sales = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/ECOMM Sales.csv')
ecomm_sales.head()

,Order ID,Order Date,Customer ID,Product ID,Sales,Quantity,Profit
0,CA-2012-124891,31/7/2012,RH-19495,TEC-AC-10003033,2309.650,7,762.1845
1,IN-2013-77878,5/2/2013,JR-16210,FUR-CH-10003950,3709.395,9,-288.7650
2,IN-2013-71249,17/10/2013,CR-12730,TEC-PH-10004664,5175.171,9,919.9710
3,ES-2013-1579342,28/1/2013,KM-16375,TEC-PH-10004583,2892.510,5,-96.5400
4,SG-2013-4320,5/11/2013,RH-9495,TEC-SHA-10000501,2832.960,8,311.5200

In [33]:
ecomm_sales['Order Date'] = pd.to_datetime(ecomm_sales['Order Date'])

<ipython-input-33-6e417639cc09>:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ecomm_sales['Order Date'] = pd.to_datetime(ecomm_sales['Order Date'])

In [34]:
ecomm_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     51290 non-null  object
 1   Order Date   51290 non-null  datetime64[ns]
 2   Customer ID  51290 non-null  object
 3   Product ID   51290 non-null  object
 4   Sales        51290 non-null  float64
 5   Quantity     51290 non-null  int64
 6   Profit       51290 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 2.7+ MB

In [35]:
ecomm_products = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/ECOMM Products.csv')
ecomm_products.head()

,Product ID,Product Name,Category,Sub-Category
0,TEC-AC-10003033,Plantronics CS510 - Over-the-Head monaural Wir...,Technology,Accessories
1,FUR-CH-10003950,"Novimex Executive Leather Armchair, Black",Furniture,Chairs
2,TEC-PH-10004664,"Nokia Smart Phone, with Caller ID",Technology,Phones
3,TEC-PH-10004583,"Motorola Smart Phone, Cordless",Technology,Phones
4,TEC-SHA-10000501,"Sharp Wireless Fax, High-Speed",Technology,Copiers

In [36]:
ecomm_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10292 entries, 0 to 10291
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    10292 non-null  object
 1   Product Name  10292 non-null  object
 2   Category      10292 non-null  object
 3   Sub-Category  10292 non-null  object
dtypes: object(4)
memory usage: 321.8+ KB

In [37]:
supershop_clients = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/Superstore Clients.csv')
supershop_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    793 non-null    object
 1   Customer Name  793 non-null    object
 2   City           793 non-null    object
 3   State          793 non-null    object
 4   Country        793 non-null    object
dtypes: object(5)
memory usage: 31.1+ KB

In [38]:
supershop_products = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/Superstore Products.csv')
supershop_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1862 entries, 0 to 1861
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    1862 non-null   object
 1   Product Name  1862 non-null   object
 2   Category      1862 non-null   object
 3   Sub-Category  1862 non-null   object
dtypes: object(4)
memory usage: 58.3+ KB

In [40]:
supershop_sales = pd.read_csv('/content/drive/MyDrive/Asistente IA Data/Superstore Sales.csv')
supershop_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order ID     9994 non-null   object
 1   Order Date   9994 non-null   object
 2   Customer ID  9994 non-null   object
 3   Product ID   9994 non-null   object
 4   Sales        9994 non-null   float64
 5   Quantity     9994 non-null   int64
 6   Profit       9994 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 546.7+ KB